export const DemoLayoutsRecipes = {
    "lg": [
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 4,
            "i": "61621a51-3ae1-4b87-b7de-42261cf174ec",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 2,
            "y": 0,
            "i": "27c41247-f759-494e-bb38-d103f854e7d1",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 8,
            "y": 0,
            "i": "056f1619-a2ca-4a30-9426-dea1b3439339",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 6,
            "y": 0,
            "i": "306e4341-9cba-4c67-96b8-601d6977fcf4",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 4,
            "y": 0,
            "i": "6aa80830-8ecc-49b7-958c-9aa6a7b89658",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 10,
            "y": 0,
            "i": "7df29237-e60f-4a29-9834-e0d196fa98e3",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 9,
            "i": "9d9995e2-ac8a-4f5a-8485-801d17143e4f",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 6,
            "y": 4,
            "i": "a6bf5db6-b76b-43af-a963-fab17017d731",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 4,
            "y": 3,
            "i": "67ae76c8-e973-43d3-8981-c99ba6400a27",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 0,
            "y": 0,
            "i": "d2901db9-8ab3-4fed-8fd2-e44238fd5e2e",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        }
    ],
    "md": [
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 3,
            "i": "61621a51-3ae1-4b87-b7de-42261cf174ec",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 2,
            "y": 0,
            "i": "27c41247-f759-494e-bb38-d103f854e7d1",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 4,
            "y": 3,
            "i": "056f1619-a2ca-4a30-9426-dea1b3439339",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 6,
            "y": 0,
            "i": "306e4341-9cba-4c67-96b8-601d6977fcf4",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 4,
            "y": 0,
            "i": "6aa80830-8ecc-49b7-958c-9aa6a7b89658",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 8,
            "y": 4,
            "i": "7df29237-e60f-4a29-9834-e0d196fa98e3",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 2,
            "y": 5,
            "i": "9d9995e2-ac8a-4f5a-8485-801d17143e4f",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 0,
            "y": 0,
            "i": "a6bf5db6-b76b-43af-a963-fab17017d731",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 6,
            "y": 4,
            "i": "67ae76c8-e973-43d3-8981-c99ba6400a27",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 8,
            "y": 0,
            "i": "d2901db9-8ab3-4fed-8fd2-e44238fd5e2e",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        }
    ],
    "sm": [
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 3,
            "i": "61621a51-3ae1-4b87-b7de-42261cf174ec",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 2,
            "y": 0,
            "i": "27c41247-f759-494e-bb38-d103f854e7d1",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 4,
            "y": 4,
            "i": "056f1619-a2ca-4a30-9426-dea1b3439339",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 4,
            "y": 0,
            "i": "306e4341-9cba-4c67-96b8-601d6977fcf4",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 0,
            "y": 0,
            "i": "6aa80830-8ecc-49b7-958c-9aa6a7b89658",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 4,
            "y": 9,
            "i": "7df29237-e60f-4a29-9834-e0d196fa98e3",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 8,
            "i": "9d9995e2-ac8a-4f5a-8485-801d17143e4f",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 2,
            "y": 5,
            "i": "a6bf5db6-b76b-43af-a963-fab17017d731",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 4,
            "y": 13,
            "i": "67ae76c8-e973-43d3-8981-c99ba6400a27",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 0,
            "y": 13,
            "i": "d2901db9-8ab3-4fed-8fd2-e44238fd5e2e",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        }
    ],
    "xs": [
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 3,
            "i": "61621a51-3ae1-4b87-b7de-42261cf174ec",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 2,
            "y": 0,
            "i": "27c41247-f759-494e-bb38-d103f854e7d1",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 8,
            "i": "056f1619-a2ca-4a30-9426-dea1b3439339",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 2,
            "y": 8,
            "i": "306e4341-9cba-4c67-96b8-601d6977fcf4",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 2,
            "y": 5,
            "i": "6aa80830-8ecc-49b7-958c-9aa6a7b89658",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 2,
            "y": 12,
            "i": "7df29237-e60f-4a29-9834-e0d196fa98e3",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 13,
            "i": "9d9995e2-ac8a-4f5a-8485-801d17143e4f",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 0,
            "y": 0,
            "i": "a6bf5db6-b76b-43af-a963-fab17017d731",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 18,
            "i": "67ae76c8-e973-43d3-8981-c99ba6400a27",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 2,
            "y": 16,
            "i": "d2901db9-8ab3-4fed-8fd2-e44238fd5e2e",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        }
    ],
    "xxs": [
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 0,
            "i": "61621a51-3ae1-4b87-b7de-42261cf174ec",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 5,
            "i": "27c41247-f759-494e-bb38-d103f854e7d1",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 10,
            "i": "056f1619-a2ca-4a30-9426-dea1b3439339",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 0,
            "y": 15,
            "i": "306e4341-9cba-4c67-96b8-601d6977fcf4",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 0,
            "y": 19,
            "i": "6aa80830-8ecc-49b7-958c-9aa6a7b89658",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 0,
            "y": 22,
            "i": "7df29237-e60f-4a29-9834-e0d196fa98e3",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 26,
            "i": "9d9995e2-ac8a-4f5a-8485-801d17143e4f",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 3,
            "x": 0,
            "y": 31,
            "i": "a6bf5db6-b76b-43af-a963-fab17017d731",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 5,
            "x": 0,
            "y": 34,
            "i": "67ae76c8-e973-43d3-8981-c99ba6400a27",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        },
        {
            "w": 2,
            "h": 4,
            "x": 0,
            "y": 39,
            "i": "d2901db9-8ab3-4fed-8fd2-e44238fd5e2e",
            "minW": 2,
            "maxW": 2,
            "minH": 2,
            "maxH": 5,
            "moved": false,
            "static": false,
            "isBounded": true
        }
    ]
}